INSERT OR IGNORE INTO District_GreatPersonPoints (DistrictType, GreatPersonClassType, PointsPerTurn)
SELECT	'DISTRICT_LIYUE_HARBOR', GreatPersonClassType, PointsPerTurn
FROM	District_GreatPersonPoints
WHERE	DistrictType = 'DISTRICT_COMMERCIAL_HUB';

INSERT OR IGNORE INTO District_TradeRouteYields (DistrictType, YieldType, YieldChangeAsOrigin, YieldChangeAsDomesticDestination, YieldChangeAsInternationalDestination)
SELECT	'DISTRICT_LIYUE_HARBOR', YieldType, YieldChangeAsOrigin, YieldChangeAsDomesticDestination, YieldChangeAsInternationalDestination
FROM	District_TradeRouteYields
WHERE	DistrictType = 'DISTRICT_COMMERCIAL_HUB';

INSERT OR IGNORE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange)
SELECT	'DISTRICT_LIYUE_HARBOR', YieldType, YieldChange
FROM	District_CitizenYieldChanges
WHERE	DistrictType = 'DISTRICT_COMMERCIAL_HUB';

INSERT INTO Types (Type, Kind)
VALUES	('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'KIND_TRAIT');

INSERT INTO CivilizationTraits (CivilizationType, TraitType)
VALUES	('CIVILIZATION_LIYUE_CL',	'TRAIT_MLGA_DISTRICT_LIYUE_HARBOR'	);

INSERT INTO Traits (TraitType, Name, Description)
VALUES	('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	NULL,	NULL	);

INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId)
VALUES	('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GOLD'		),
		('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GPP'		),
		('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_SHIPYARD_BANK_GOLD'			),
		('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_SHIPYARD_BANK_GPP'			),
		('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GOLD'	),
		('TRAIT_MLGA_DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GPP'	);

INSERT INTO DistrictModifiers (DistrictType, ModifierId)
VALUES	('DISTRICT_LIYUE_HARBOR',	'MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_TRC'	);

INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
VALUES	('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GOLD',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'	,NULL),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_TRC',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY','BUILDING_IS_LIGHTHOUSE'),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GPP',		'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		'BUILDING_IS_LIGHTHOUSE'),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GOLD',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',	NULL),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GPP',			'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',		'BUILDING_IS_SHIPYARD'),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GOLD',	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',NULL),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GPP',	'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT',	'BUILDING_IS_SEAPORT');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GOLD',	'BuildingType',			'BUILDING_LIGHTHOUSE'			),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GOLD',	'YieldType',			'YIELD_GOLD'					),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GOLD',	'Amount',				2								),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_TRC',		'Amount',				1								),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GPP',		'GreatPersonClassType',	'GREAT_PERSON_CLASS_MERCHANT'	),
		('MOD_MLGA_BUILDING_LIGHTHOUSE_MARKET_GPP',		'Amount',				1								),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GOLD',		'BuildingType',			'BUILDING_SHIPYARD'				),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GOLD',		'YieldType',			'YIELD_GOLD'					),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GOLD',		'Amount',				5								),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GPP',			'GreatPersonClassType',	'GREAT_PERSON_CLASS_MERCHANT'	),
		('MOD_MLGA_BUILDING_SHIPYARD_BANK_GPP',			'Amount',				1								),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GOLD',	'BuildingType',			'BUILDING_SEAPORT'				),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GOLD',	'YieldType',			'YIELD_GOLD'					),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GOLD',	'Amount',				11								),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GPP',	'GreatPersonClassType',	'GREAT_PERSON_CLASS_MERCHANT'	),
		('MOD_MLGA_BUILDING_SEAPORT_STOCK_EXCHANGE_GPP',	'Amount',				1								);